name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t ghcr.io/testingautomated-usi/bisupervised:$(date +%s)
      
    - name: Publish to github container repository
      run: docker push ghcr.io/testingautomated-usi/bisupervised:$(date +%s)
